---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleappjavadeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleappjava
  template:
    metadata:
      labels:
        app: sampleappjava
    spec:
      containers:
      - name: sampleappcontainers
        image: tomcat
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: sampleappjavasvc
  labels:
    app: sampleappjava
spec:
  selector:
    app: sampleappjava
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 8080
